services:
  - type: web
    name: rk-seo-proxy
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SHOPIFY_CLIENT_ID
        sync: false
      - key: SHOPIFY_CLIENT_SECRET
        sync: false
      - key: SHOPIFY_STORE_DOMAIN
        value: rudrakailash.myshopify.com
      - key: APP_URL
        sync: false
      - key: SHOPIFY_ACCESS_TOKEN
        sync: false
      - key: PORT
        value: 3001
